### ISSUE TITLE
Throws an exception

### ISSUE THREAD

**Issue by ForbesLindesay** [zemirco/primus-express-session#2]
When I tried to use this, I got the exception:

``` js
 if (0 == str.indexOf('j:')) {
               ^
TypeError: Cannot call method 'indexOf' of undefined
    at Object.exports.parseJSONCookie (/Users/forbeslindesay/GitHub/rooms/node_modules/primus-express-session/node_modules/connect/lib/utils.js:230:16)
    at Sparky.Spark.getSession (/Users/forbeslindesay/GitHub/rooms/node_modules/primus-express-session/index.js:37:27)
    at Sparky.<anonymous> (/Users/forbeslindesay/GitHub/rooms/server.js:178:13)
    at Sparky.EventEmitter.emit (events.js:98:17)
    at decoding (/Users/forbeslindesay/GitHub/rooms/node_modules/primus/spark.js:215:13)
    at Sparky.decoder (/Users/forbeslindesay/GitHub/rooms/node_modules/primus/parsers/json.js:32:3)
    at Sparky.message (/Users/forbeslindesay/GitHub/rooms/node_modules/primus/spark.js:188:20)
    at Sparky.EventEmitter.emit (events.js:95:17)
    at Socket.emit (/Users/forbeslindesay/GitHub/rooms/node_modules/primus/spark.js:346:11)
    at Socket.EventEmitter.emit (events.js:95:17)
```

**Comment by zemirco** [comment]
I assume you're using it with Express 4.x and the current Primus version?

**Comment by zemirco** [comment]
Hey @ForbesLindesay ,

I created a branch for Express 4.x and newer versions of Primus. You don't need my plugin anymore. Take a look at the [docs](https://github.com/zemirco/primus-express-session/tree/express_4.x#important).

Hope that helps!

**Comment by ForbesLindesay** [comment]
Yes, I was using express 4.0.  Thanks for the update.
